# Prepared Narrative Geopolitics intake commands for 2026-08-28 YouTube capture.
# Generated from youtube-capture queue only. Running commands in the landing section
# will mutate archive source files and the source manifest.

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

# Preflight: warning-free queue drafts, including manual two-voice routing for Wilkerson/Johnson.

.\tools\run.ps1 intake-land --date 2026-08-28 --quick --title "Impeachment Looms Over Trump After the Pentagon’s Leaked Nuclear Plans. Joe Kent on What Comes Next." --url "https://www.youtube.com/watch?v=9POOfL7fo7c" --host-slug tucker-carlson --voice-slug kent --pub-date 2026-08-28 --source-form interview --source-class "guest interview pressure test" --body-file "narrative-geopolitics\work\capture\youtube\transcripts\2026-08-28\tucker-carlson-impeachment-trump-pentagons-leaked-nuclear-plans-joe-kent.txt" --trim-opening auto --asr-repair auto --sectioning none --preflight --json
.\tools\run.ps1 intake-land --date 2026-08-28 --quick --title "Iran May Beat the US to the Punch in WAR /Trita Parsi & Lt Col Daniel Davis" --url "https://www.youtube.com/watch?v=9Xa7Chtgf70" --host-slug daniel-davis --voice-slug parsi --pub-date 2026-08-28 --source-form interview --source-class "guest interview pressure test" --body-file "narrative-geopolitics\work\capture\youtube\transcripts\2026-08-28\iran-may-beat-the-us-to-the-punch-in-war-trita-parsi-daniel-davis.txt" --trim-opening auto --asr-repair auto --sectioning none --preflight --json
.\tools\run.ps1 intake-land --date 2026-08-28 --quick --title "Russia Donbas Knockout Blow Dobropilia Cauldron Slaviansk Crisis; Lavrov West Diplomacy All Trickery" --url "https://www.youtube.com/watch?v=RLF6vPwXKsg" --host-slug alexander-mercouris --voice-slug mercouris --pub-date 2026-08-28 --source-form interview --source-class "guest interview pressure test" --body-file "narrative-geopolitics\work\capture\youtube\transcripts\2026-08-28\russia-donbas-knockout-blow-dobropilia-cauldron-slaviansk-crisis-lavrov-west-diplomacy.txt" --trim-opening auto --asr-repair auto --sectioning none --preflight --json
.\tools\run.ps1 intake-land --date 2026-08-28 --quick --title "John Mearsheimer: Russia & Iran - The West’s Escalation Trap" --url "https://www.youtube.com/watch?v=2jxda4WTcbc" --host-slug glenn-diesen --voice-slug mearsheimer --pub-date 2026-08-28 --source-form interview --source-class "guest interview pressure test" --body-file "narrative-geopolitics\work\capture\youtube\transcripts\2026-08-28\john-mearsheimer-russia-iran-the-wests-escalation-trap.txt" --trim-opening auto --asr-repair auto --sectioning none --preflight --json
.\tools\run.ps1 intake-land --date 2026-08-28 --quick --title "Max Blumenthal: Netanyahu's Dangerous Game in Britain" --url "https://www.youtube.com/watch?v=iqWBiVpxeSc" --host-slug judging-freedom --voice-slug blumenthal --pub-date 2026-08-28 --source-form interview --source-class "guest interview pressure test" --body-file "narrative-geopolitics\work\capture\youtube\transcripts\2026-08-28\max-blumenthal-netanyahus-dangerous-game-in-britain.txt" --trim-opening auto --asr-repair auto --sectioning none --preflight --json
.\tools\run.ps1 intake-land --date 2026-08-28 --quick --title "The Truth About the US Blockade in the Strait of Hormuz" --url "https://www.youtube.com/watch?v=EPiupy195bc" --host-slug judging-freedom --voice-slug escobar --pub-date 2026-08-28 --source-form interview --source-class "guest interview pressure test" --body-file "narrative-geopolitics\work\capture\youtube\transcripts\2026-08-28\the-truth-about-the-us-blockade-in-the-strait-of-hormuz.txt" --trim-opening auto --asr-repair auto --sectioning none --preflight --json
.\tools\run.ps1 intake-land --date 2026-08-28 --quick --title "Amb. Chas Freeman: Crumbling on All Sides: The Staggering Reality of Israel's Multi-Front War" --url "https://www.youtube.com/watch?v=1F-YSL_yyuU" --host-slug dialogue-works --guest "Chas Freeman" --voice-slug freeman --pub-date 2026-08-28 --source-form interview --source-class "guest interview pressure test" --body-file "narrative-geopolitics\work\capture\youtube\transcripts\2026-08-28\amb-chas-freeman-crumbling-on-all-sides-israels-multifront-war.txt" --trim-opening auto --asr-repair auto --sectioning none --preflight --json
.\tools\run.ps1 intake-land --date 2026-08-28 --quick --title "Col. Larry Wilkerson & Larry Johnson: The Trap is Closing on Iran and the US" --url "https://www.youtube.com/watch?v=El-b1LRgihQ" --host-slug dialogue-works --voice-slug wilkerson --voice-slug johnson --pub-date 2026-08-28 --source-form interview --source-class "guest interview pressure test" --body-file "narrative-geopolitics\work\capture\youtube\transcripts\2026-08-28\col-larry-wilkerson-larry-johnson-trap-closing-on-iran-us.txt" --trim-opening auto --asr-repair auto --sectioning none --preflight --json
.\tools\run.ps1 intake-land --date 2026-08-28 --quick --title "U.S PLAN TO RESART IRAN WAR AFTER THE MIDTERMS, TRUMP CLAIMS HE CONTROL STRAIT w/ COL DANIEL DAVIS" --url "https://www.youtube.com/watch?v=ChcqxvGKkms" --host-slug moral-resistance --voice-slug davis --pub-date 2026-08-28 --source-form interview --source-class "guest interview pressure test" --body-file "narrative-geopolitics\work\capture\youtube\transcripts\2026-08-28\moral-resistance-us-plan-to-restart-iran-war-daniel-davis.txt" --trim-opening auto --asr-repair auto --sectioning none --preflight --json
.\tools\run.ps1 intake-land --date 2026-08-28 --quick --title "BREAKING: MULTIPLE STRIKES ON STRIAT OF HORMUZ, HEGSETH FOR PRESIDENT w/ CIA Larry Johnson" --url "https://www.youtube.com/watch?v=c-dSAEWep6k" --host-slug moral-resistance --voice-slug johnson --pub-date 2026-08-28 --source-form interview --source-class "guest interview pressure test" --body-file "narrative-geopolitics\work\capture\youtube\transcripts\2026-08-28\moral-resistance-multiple-strikes-on-strait-of-hormuz-larry-johnson.txt" --trim-opening auto --asr-repair auto --sectioning none --preflight --json
.\tools\run.ps1 intake-land --date 2026-08-28 --quick --title "NATO's Crazy Long Term Planning for Proxy Wars | Stas Krapivnik" --url "https://www.youtube.com/watch?v=47JG9LuXYdY" --host-slug neutrality-studies --voice-slug krapivnik --pub-date 2026-08-28 --source-form interview --source-class "guest interview pressure test" --body-file "narrative-geopolitics\work\capture\youtube\transcripts\2026-08-28\neutrality-studies-nato-long-term-planning-proxy-wars-stas-krapivnik.txt" --trim-opening auto --asr-repair auto --sectioning none --preflight --json
.\tools\run.ps1 intake-land --date 2026-08-28 --quick --title "A FOREIGN SPY CHIEF INSIDE A PRESIDENT-LINKED BANK — w/ Robert Barnes" --url "https://www.youtube.com/watch?v=jfnYC1Aoepk" --host-slug mario-nawfal --voice-slug barnes --pub-date 2026-08-28 --source-form interview --source-class "guest interview pressure test" --body-file "narrative-geopolitics\work\capture\youtube\transcripts\2026-08-28\mario-nawfal-robert-barnes-foreign-spy-chief-president-linked-bank.txt" --host-people "Brandon Weichert" --guest "Robert Barnes" --trim-opening auto --asr-repair auto --sectioning none --preflight --json

# Landing: run only after explicit archive-admission authority.

.\tools\run.ps1 intake-land --date 2026-08-28 --quick --title "Impeachment Looms Over Trump After the Pentagon’s Leaked Nuclear Plans. Joe Kent on What Comes Next." --url "https://www.youtube.com/watch?v=9POOfL7fo7c" --host-slug tucker-carlson --voice-slug kent --pub-date 2026-08-28 --source-form interview --source-class "guest interview pressure test" --body-file "narrative-geopolitics\work\capture\youtube\transcripts\2026-08-28\tucker-carlson-impeachment-trump-pentagons-leaked-nuclear-plans-joe-kent.txt" --trim-opening auto --asr-repair auto --sectioning none
.\tools\run.ps1 intake-land --date 2026-08-28 --quick --title "Iran May Beat the US to the Punch in WAR /Trita Parsi & Lt Col Daniel Davis" --url "https://www.youtube.com/watch?v=9Xa7Chtgf70" --host-slug daniel-davis --voice-slug parsi --pub-date 2026-08-28 --source-form interview --source-class "guest interview pressure test" --body-file "narrative-geopolitics\work\capture\youtube\transcripts\2026-08-28\iran-may-beat-the-us-to-the-punch-in-war-trita-parsi-daniel-davis.txt" --trim-opening auto --asr-repair auto --sectioning none
.\tools\run.ps1 intake-land --date 2026-08-28 --quick --title "Russia Donbas Knockout Blow Dobropilia Cauldron Slaviansk Crisis; Lavrov West Diplomacy All Trickery" --url "https://www.youtube.com/watch?v=RLF6vPwXKsg" --host-slug alexander-mercouris --voice-slug mercouris --pub-date 2026-08-28 --source-form interview --source-class "guest interview pressure test" --body-file "narrative-geopolitics\work\capture\youtube\transcripts\2026-08-28\russia-donbas-knockout-blow-dobropilia-cauldron-slaviansk-crisis-lavrov-west-diplomacy.txt" --trim-opening auto --asr-repair auto --sectioning none
.\tools\run.ps1 intake-land --date 2026-08-28 --quick --title "John Mearsheimer: Russia & Iran - The West’s Escalation Trap" --url "https://www.youtube.com/watch?v=2jxda4WTcbc" --host-slug glenn-diesen --voice-slug mearsheimer --pub-date 2026-08-28 --source-form interview --source-class "guest interview pressure test" --body-file "narrative-geopolitics\work\capture\youtube\transcripts\2026-08-28\john-mearsheimer-russia-iran-the-wests-escalation-trap.txt" --trim-opening auto --asr-repair auto --sectioning none
.\tools\run.ps1 intake-land --date 2026-08-28 --quick --title "Max Blumenthal: Netanyahu's Dangerous Game in Britain" --url "https://www.youtube.com/watch?v=iqWBiVpxeSc" --host-slug judging-freedom --voice-slug blumenthal --pub-date 2026-08-28 --source-form interview --source-class "guest interview pressure test" --body-file "narrative-geopolitics\work\capture\youtube\transcripts\2026-08-28\max-blumenthal-netanyahus-dangerous-game-in-britain.txt" --trim-opening auto --asr-repair auto --sectioning none
.\tools\run.ps1 intake-land --date 2026-08-28 --quick --title "The Truth About the US Blockade in the Strait of Hormuz" --url "https://www.youtube.com/watch?v=EPiupy195bc" --host-slug judging-freedom --voice-slug escobar --pub-date 2026-08-28 --source-form interview --source-class "guest interview pressure test" --body-file "narrative-geopolitics\work\capture\youtube\transcripts\2026-08-28\the-truth-about-the-us-blockade-in-the-strait-of-hormuz.txt" --trim-opening auto --asr-repair auto --sectioning none
.\tools\run.ps1 intake-land --date 2026-08-28 --quick --title "Amb. Chas Freeman: Crumbling on All Sides: The Staggering Reality of Israel's Multi-Front War" --url "https://www.youtube.com/watch?v=1F-YSL_yyuU" --host-slug dialogue-works --guest "Chas Freeman" --voice-slug freeman --pub-date 2026-08-28 --source-form interview --source-class "guest interview pressure test" --body-file "narrative-geopolitics\work\capture\youtube\transcripts\2026-08-28\amb-chas-freeman-crumbling-on-all-sides-israels-multifront-war.txt" --trim-opening auto --asr-repair auto --sectioning none
.\tools\run.ps1 intake-land --date 2026-08-28 --quick --title "Col. Larry Wilkerson & Larry Johnson: The Trap is Closing on Iran and the US" --url "https://www.youtube.com/watch?v=El-b1LRgihQ" --host-slug dialogue-works --voice-slug wilkerson --voice-slug johnson --pub-date 2026-08-28 --source-form interview --source-class "guest interview pressure test" --body-file "narrative-geopolitics\work\capture\youtube\transcripts\2026-08-28\col-larry-wilkerson-larry-johnson-trap-closing-on-iran-us.txt" --trim-opening auto --asr-repair auto --sectioning none
.\tools\run.ps1 intake-land --date 2026-08-28 --quick --title "U.S PLAN TO RESART IRAN WAR AFTER THE MIDTERMS, TRUMP CLAIMS HE CONTROL STRAIT w/ COL DANIEL DAVIS" --url "https://www.youtube.com/watch?v=ChcqxvGKkms" --host-slug moral-resistance --voice-slug davis --pub-date 2026-08-28 --source-form interview --source-class "guest interview pressure test" --body-file "narrative-geopolitics\work\capture\youtube\transcripts\2026-08-28\moral-resistance-us-plan-to-restart-iran-war-daniel-davis.txt" --trim-opening auto --asr-repair auto --sectioning none
.\tools\run.ps1 intake-land --date 2026-08-28 --quick --title "BREAKING: MULTIPLE STRIKES ON STRIAT OF HORMUZ, HEGSETH FOR PRESIDENT w/ CIA Larry Johnson" --url "https://www.youtube.com/watch?v=c-dSAEWep6k" --host-slug moral-resistance --voice-slug johnson --pub-date 2026-08-28 --source-form interview --source-class "guest interview pressure test" --body-file "narrative-geopolitics\work\capture\youtube\transcripts\2026-08-28\moral-resistance-multiple-strikes-on-strait-of-hormuz-larry-johnson.txt" --trim-opening auto --asr-repair auto --sectioning none
.\tools\run.ps1 intake-land --date 2026-08-28 --quick --title "NATO's Crazy Long Term Planning for Proxy Wars | Stas Krapivnik" --url "https://www.youtube.com/watch?v=47JG9LuXYdY" --host-slug neutrality-studies --voice-slug krapivnik --pub-date 2026-08-28 --source-form interview --source-class "guest interview pressure test" --body-file "narrative-geopolitics\work\capture\youtube\transcripts\2026-08-28\neutrality-studies-nato-long-term-planning-proxy-wars-stas-krapivnik.txt" --trim-opening auto --asr-repair auto --sectioning none
.\tools\run.ps1 intake-land --date 2026-08-28 --quick --title "A FOREIGN SPY CHIEF INSIDE A PRESIDENT-LINKED BANK — w/ Robert Barnes" --url "https://www.youtube.com/watch?v=jfnYC1Aoepk" --host-slug mario-nawfal --voice-slug barnes --pub-date 2026-08-28 --source-form interview --source-class "guest interview pressure test" --body-file "narrative-geopolitics\work\capture\youtube\transcripts\2026-08-28\mario-nawfal-robert-barnes-foreign-spy-chief-president-linked-bank.txt" --host-people "Brandon Weichert" --guest "Robert Barnes" --trim-opening auto --asr-repair auto --sectioning none
