from __future__ import annotations

import argparse
import json
import re
from pathlib import Path
from typing import Any


REPO_ROOT = Path(__file__).resolve().parent.parent
TRACKER_ROOT = REPO_ROOT / "narrative-geopolitics" / "work" / "system-improvement"
LEDGER_JSON_PATH = TRACKER_ROOT / "recursive-learning-ledger.json"
LEDGER_MD_PATH = TRACKER_ROOT / "recursive-learning-ledger.md"

ENTRY_ID_RE = re.compile(r"^RSI-\d{8}-\d{2}$")
COMMIT_RE = re.compile(r"^[0-9a-f]{7,40}$")
REQUIRED_STAGES = ("observation", "diagnosis", "intervention", "validation", "outcome")
ALLOWED_CLASSES = {
    "closed-feedback-loop",
    "recursive-governance",
    "partial-feedback-loop",
}
ALLOWED_CLOSURE_STATES = {"validated", "measured", "partial", "superseded"}


def load_ledger(path: Path = LEDGER_JSON_PATH) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def render_markdown(ledger: dict[str, Any]) -> str:
    entries = sorted(ledger.get("entries", []), key=lambda item: item["id"])
    lines = [
        "# Recursive Learning Ledger",
        "",
        "Generated from `recursive-learning-ledger.json`. Do not edit this file directly.",
        "",
        f"Status: `{ledger.get('status', '')}`",
        "",
        str(ledger.get("scope_note", "")),
        "",
        "Method: [recursive-learning-ledger.md](../../method/recursive-learning-ledger.md)",
        "",
        "## Entries",
        "",
        "| ID | Date | Class | Closure | Improvement |",
        "| --- | --- | --- | --- | --- |",
    ]
    for entry in entries:
        lines.append(
            f"| `{entry['id']}` | `{entry['date']}` | `{entry['class']}` | "
            f"`{entry['closure_state']}` | {entry['title']} |"
        )
    for entry in entries:
        lines.extend(
            [
                "",
                f"## `{entry['id']}` — {entry['title']}",
                "",
                f"- Class: `{entry['class']}`",
                f"- Closure: `{entry['closure_state']}`",
            ]
        )
        for stage_name in REQUIRED_STAGES:
            stage = entry[stage_name]
            lines.extend(
                [
                    "",
                    f"### {stage_name.title()}",
                    "",
                    stage["summary"],
                    "",
                    "Evidence:",
                    "",
                    *(
                        f"- [`{path}`](../../../{path})"
                        for path in stage["evidence_paths"]
                    ),
                ]
            )
            if stage_name == "intervention":
                commits = ", ".join(f"`{value}`" for value in stage["commits"])
                lines.extend(["", f"Commits: {commits}."])
            if stage_name == "outcome":
                lines.extend(["", f"Measure: {stage['measure']}"])
        lines.extend(
            [
                "",
                "### Next Measure",
                "",
                entry["next_measure"],
            ]
        )
    return "\n".join(lines).rstrip() + "\n"


def _duplicate_values(values: list[str]) -> list[str]:
    seen: set[str] = set()
    duplicates: set[str] = set()
    for value in values:
        if value in seen:
            duplicates.add(value)
        seen.add(value)
    return sorted(duplicates)


def validate_ledger(
    *,
    repo_root: Path = REPO_ROOT,
    json_path: Path = LEDGER_JSON_PATH,
    markdown_path: Path = LEDGER_MD_PATH,
) -> list[str]:
    failures: list[str] = []
    if not json_path.is_file():
        return [f"recursive learning ledger missing: {json_path}"]
    try:
        ledger = json.loads(json_path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as error:
        return [f"recursive learning ledger invalid JSON: line {error.lineno}"]

    entries = ledger.get("entries")
    if not isinstance(entries, list):
        return ["recursive learning ledger missing entries list"]
    entry_ids = [str(entry.get("id", "")) for entry in entries if isinstance(entry, dict)]
    for duplicate in _duplicate_values(entry_ids):
        failures.append(f"duplicate recursive learning ID: {duplicate}")

    for entry in entries:
        if not isinstance(entry, dict):
            failures.append("recursive learning ledger contains non-object entry")
            continue
        entry_id = str(entry.get("id", ""))
        if not ENTRY_ID_RE.fullmatch(entry_id):
            failures.append(f"invalid recursive learning ID: {entry_id or '<missing>'}")
        if entry.get("class") not in ALLOWED_CLASSES:
            failures.append(f"{entry_id}: invalid class")
        if entry.get("closure_state") not in ALLOWED_CLOSURE_STATES:
            failures.append(f"{entry_id}: invalid closure_state")
        if not str(entry.get("title", "")).strip() or not str(entry.get("next_measure", "")).strip():
            failures.append(f"{entry_id}: missing title or next_measure")

        for stage_name in REQUIRED_STAGES:
            stage = entry.get(stage_name)
            if not isinstance(stage, dict):
                failures.append(f"{entry_id}: missing {stage_name} stage")
                continue
            if not str(stage.get("summary", "")).strip():
                failures.append(f"{entry_id}: {stage_name} missing summary")
            paths = stage.get("evidence_paths")
            if not isinstance(paths, list) or not paths:
                failures.append(f"{entry_id}: {stage_name} missing evidence_paths")
            else:
                for raw_path in paths:
                    path = repo_root / str(raw_path)
                    if not path.exists():
                        failures.append(f"{entry_id}: missing evidence path: {raw_path}")
            if stage_name == "intervention":
                commits = stage.get("commits")
                if not isinstance(commits, list) or not commits:
                    failures.append(f"{entry_id}: intervention missing commits")
                else:
                    for commit in commits:
                        if not COMMIT_RE.fullmatch(str(commit)):
                            failures.append(f"{entry_id}: invalid commit reference: {commit}")
            if stage_name == "outcome" and not str(stage.get("measure", "")).strip():
                failures.append(f"{entry_id}: outcome missing measure")

        if entry.get("closure_state") == "measured":
            measure = str(entry.get("outcome", {}).get("measure", "")).casefold()
            if "pending" in measure:
                failures.append(f"{entry_id}: measured entry has pending outcome")
        if entry.get("class") == "partial-feedback-loop" and entry.get("closure_state") != "partial":
            failures.append(f"{entry_id}: partial feedback loop must have partial closure")

    if not markdown_path.is_file():
        failures.append(f"recursive learning Markdown missing: {markdown_path}")
    elif markdown_path.read_text(encoding="utf-8") != render_markdown(ledger):
        failures.append("recursive learning Markdown drift from canonical JSON")
    return failures


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Render or validate the recursive learning ledger.")
    parser.add_argument("--write", action="store_true", help="Regenerate Markdown from canonical JSON.")
    parser.add_argument("--check", action="store_true", help="Validate the canonical ledger and Markdown view.")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    if args.write:
        LEDGER_MD_PATH.write_text(
            render_markdown(load_ledger()),
            encoding="utf-8",
            newline="\n",
        )
    failures = validate_ledger() if args.check or not args.write else []
    for failure in failures:
        print(f"FAIL {failure}")
    if not failures:
        print("recursive_learning_ledger=valid")
    return 1 if failures else 0


if __name__ == "__main__":
    raise SystemExit(main())
