"""Report historical-reference density across Chas Freeman transcripts."""
from __future__ import annotations

import argparse
import importlib.util
import sys
from collections import Counter, defaultdict
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
OUTPUT_PATH = REPO_ROOT / "narrative-geopolitics" / "voices" / "freeman" / "historical-reference-density.md"
INDEX_SCRIPT = REPO_ROOT / "scripts" / "build_freeman_historical_index.py"


def load_index_module():
    spec = importlib.util.spec_from_file_location("freeman_historical_index", INDEX_SCRIPT)
    if not spec or not spec.loader:
        raise RuntimeError("Unable to load Freeman historical index builder")
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


def transcript_word_count(module, row: dict) -> int:
    path = row["full_path"]
    if not path.is_file():
        return 0
    return len(module.re.findall(r"\S+", module.source_body(path.read_text(encoding="utf-8", errors="replace")))
               )


def build_report() -> str:
    module = load_index_module()
    rows = module.source_rows()
    occurrences, coverage = module.build_occurrences()
    by_source: dict[str, list[dict]] = defaultdict(list)
    for occurrence in occurrences:
        by_source[occurrence["source_id"]].append(occurrence)

    records = []
    for index, row in enumerate(rows, start=1):
        source_id = f"SRC-FR-{index:03d}"
        words = transcript_word_count(module, row)
        refs = by_source.get(source_id, [])
        categories = {item["rule"].key for item in refs}
        confidence = Counter(item["confidence"] for item in refs)
        records.append({
            "source_id": source_id,
            "date": str(row.get("date") or ""),
            "title": str(row.get("title") or ""),
            "host": str(row.get("host_slug") or ""),
            "words": words,
            "references": len(refs),
            "per_k": (len(refs) / words * 1000) if words else 0.0,
            "categories": len(categories),
            "confidence": confidence,
        })

    total_words = sum(item["words"] for item in records)
    total_refs = sum(item["references"] for item in records)
    total_categories = len({item["rule"].key for item in occurrences})
    confidence_total = Counter(item["confidence"] for item in occurrences)
    ranked = sorted(records, key=lambda item: (-item["per_k"], item["date"], item["source_id"]))
    host_stats: dict[str, list[dict]] = defaultdict(list)
    for record in records:
        host_stats[record["host"]].append(record)

    lines = [
        "# Chas Freeman Historical-Reference Density",
        "",
        "Generated by `scripts/report_freeman_reference_density.py` from the manifest-backed historical-reference index.",
        "",
        "## Metric contract",
        "",
        "- Primary metric: historical-reference occurrences per 1,000 transcript words.",
        "- Secondary metrics: raw occurrences, unique reference categories, and attribution-confidence mix.",
        "- Counts are source-derived and inherit archive transcript quality; they are not measures of historical accuracy.",
        "",
        "## Corpus summary",
        "",
        f"- Transcripts: **{len(records)}**",
        f"- Transcript words: **{total_words:,}**",
        f"- Historical-reference occurrences: **{total_refs:,}**",
        f"- Unique reference categories: **{total_categories}**",
        f"- Corpus density: **{(total_refs / total_words * 1000) if total_words else 0:.2f} per 1,000 words**",
        f"- Attribution confidence: direct `{confidence_total['direct']}`, strong-inferred `{confidence_total['strong-inferred']}`, provisional `{confidence_total['provisional']}`",
        "",
        "## Transcript density",
        "",
        "| Source | Date | Host/channel | Words | References | Per 1,000 words | Unique categories | Confidence mix | Title |",
        "| --- | --- | --- | ---: | ---: | ---: | ---: | --- | --- |",
    ]
    for item in ranked:
        mix = ", ".join(f"{key}:{value}" for key, value in sorted(item["confidence"].items())) or "none"
        lines.append(f"| `{item['source_id']}` | {item['date']} | `{item['host']}` | {item['words']:,} | {item['references']} | {item['per_k']:.2f} | {item['categories']} | {mix} | {item['title']} |")

    lines += ["", "## Host/channel summary", "", "| Host/channel | Transcripts | Words | References | Per 1,000 words | Mean categories / transcript |", "| --- | ---: | ---: | ---: | ---: | ---: |"]
    for host, items in sorted(host_stats.items()):
        words = sum(item["words"] for item in items)
        refs = sum(item["references"] for item in items)
        mean_categories = sum(item["categories"] for item in items) / len(items)
        lines.append(f"| `{host}` | {len(items)} | {words:,} | {refs} | {(refs / words * 1000) if words else 0:.2f} | {mean_categories:.2f} |")

    lines += ["", "## Interpretation guardrails", "", "- Compare rates only when transcript capture quality and attribution confidence are reasonably comparable.", "- High density may reflect a historical discussion, a long transcript, or repeated ASR fragments; inspect the occurrence ledger before interpreting it as a voice trait.", "- This report measures Freeman first. Cross-voice comparison is a separate report with its own coverage and normalization audit.", "", "## Coverage log", "", *[f"- {item}" for item in coverage], ""]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=OUTPUT_PATH)
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()
    report = build_report()
    if args.dry_run:
        print(report)
    else:
        args.output.write_text(report, encoding="utf-8", newline="\n")
        print(f"Wrote {args.output.relative_to(REPO_ROOT).as_posix()}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
